### Get all employees
GET http://localhost:1234/employees
### Get all employees by type
GET http://localhost:1234/employees?type=vendedor
### Get employee by ID
GET http://localhost:1234/employees/3c0550fc-81c3-11ee-b53e-eaf15ba8dff1
### Create employee
POST http://localhost:1234/employees
Content-Type: application/json

{
  "employeeType": "Vendedor",
  "firstName": "Emily",
  "secondName": "",
  "lastName": "Johnson",
  "idNumber": "0801200203580",
  "phoneNumber": 12345678,
  "email": "emily@litoral.com",
  "profilePictureUrl": "https://randomuser.me/api/portraits/women/81.jpg",
  "address": "San Pedro Sula"
}

### Create employee with errors
POST http://localhost:1234/employees
Content-Type: application/json

{
  "employeeType": "Supervisor",
  "secondName": "Alejandro",
  "lastName": "Corrales",
  "idNumber": "0511201103483",
  "phoneNumber": 12345678,
  "email": "daniel@litoral.com",
  "profilePictureUrl": "https://randomuser.me/api/portraits/men/80.jpg"
}

### Update employee
PATCH http://localhost:1234/employees/3c0550fc-81c3-11ee-b53e-eaf15ba8dff1
Content-Type: application/json

{
  "employeeType": "Gerente"
}

### Delete employee
DELETE http://localhost:1234/employees/3c0550fc-81c3-11ee-b53e-eaf15ba8dff1