### Get all sales
GET http://localhost:1234/sales
### Get sales by seller
GET http://localhost:1234/sales?sellerId=87b39f15-81a2-11ee-be2b-900f0c66a857
### Get sales by dates
GET http://localhost:1234/sales?initialDate=2023-11-15&endDate=2023-11-30
### Get sales by id and dates
GET http://localhost:1234/sales?sellerId=87b39f15-81a2-11ee-be2b-900f0c66a857&initialDate=2023-11-1&endDate=2023-11-30
### Get sales by id
GET http://localhost:1234/sales/0db66467-834e-11ee-9ed4-900f0c66a857
### Create a new sale
POST http://localhost:1234/sales
Content-Type: application/json

{
  "seller": "Michael Brown",
  "sellerId": "5",
  "date": "2023-11-14T23:39:08.498Z" ,
  "items": [
    {
      "name": "Steak",
      "price": 19.99,
      "quantity": 1
    },
    {
      "name": "Baked Potato",
      "price": 7.49,
      "quantity": 2
    }
  ],
  "subtotal": 34.97,
  "taxes": 6.64,
  "total": 41.61,
  "sql": "drop database restaurant;"
}

### Delete sale
DELETE http://localhost:1234/sales/8b5b36b2-4a2a-4d6c-9cf2-dca64453cb16