### Get all sales
GET http://localhost:1234/sales
### Get sales by seller
GET http://localhost:1234/sales?sellerId=87b39f15-81a2-11ee-be2b-900f0c66a857
### Get sales by dates
GET http://localhost:1234/sales?initialDate=2023-11-15&endDate=2023-11-30
### Get sales by id and dates
GET http://localhost:1234/sales?sellerId=87b39f15-81a2-11ee-be2b-900f0c66a857&initialDate=2023-11-1&endDate=2023-11-30
### Get sales by id
GET http://localhost:1234/sales/88294e7d-8361-11ee-9ed4-900f0c66a857
### Create a new sale
POST http://localhost:1234/sales
Content-Type: application/json

{
  "seller": "Alice Smith",
  "sellerId": "d313cf29-834b-11ee-9ed4-900f0c66a857",
  "date": "2023-11-14T23:39:08.498Z" ,
  "items": [
    {
      "name": "Tacos",
      "price": 10.99,
      "quantity": 1
    },
    {
      "name": "Tiramisu",
      "price": 6.99,
      "quantity": 2
    }
  ],
  "subtotal": 24.97,
  "taxes": 3.75,
  "total": 28.72,
  "sql": "drop database restaurant;"
}

### Delete sale
DELETE http://localhost:1234/sales/8eab2a85-85bc-11ee-a692-900f0c66a857