### Get all sales
GET http://localhost:1234/sales
### Get sales by seller
GET http://localhost:1234/sales?sellerId=87b39f15-81a2-11ee-be2b-900f0c66a857
### Get sales by dates
GET http://localhost:1234/sales?initialDate=2023-11-15&endDate=2023-11-30
### Get sales by id and dates
GET http://localhost:1234/sales?sellerId=87b39f15-81a2-11ee-be2b-900f0c66a857&initialDate=2023-11-1&endDate=2023-11-30
### Get sales by id
GET http://localhost:1234/sales/15d8631c-8704-11ee-b53e-eaf15ba8dff1

### Create a new sale
POST http://localhost:1234/sales
Content-Type: application/json

{
    "seller": "Alice Smith",
    "sellerId": "9cfeab80-834b-11ee-b53e-eaf15ba8dff1",
    "date": "2023-07-12T19:45:30.123Z",
    "status": "Pendiente",
    "items": [
      {
        "name": "Nachos",
        "price": 6.99,
        "quantity": 2
      },
      {
        "name": "Hamburguesa",
        "price": 9.99,
        "quantity": 1
      }
    ],
    "subtotal": 23.97,
    "taxes": 3.59,
    "total": 27.56
  }

### Delete sale
DELETE http://localhost:1234/sales/8eab2a85-85bc-11ee-a692-900f0c66a857