### Home
GET http://localhost:1234
### Customers
GET http://localhost:1234/customers
### Customers by ID
GET http://localhost:1234/customers/e96841f0-80e8-11ee-b53e-eaf15ba8dff1
### Customers by address
GET http://localhost:1234/customers?address=Villanueva
### Crear un customer
POST http://localhost:1234/customers
Content-Type: application/json

{
  "firstName": "Brian",
  "secondName": "Josue",
  "lastName": "Ramos",
  "email": "brian@gmail.com",
  "password": "admin123",
  "phoneNumber": 12345678,
  "address": "San Pedro Sula"
}
### Crear un customer con errores
POST http://localhost:1234/customers
Content-Type: application/json

{
  "firstName": "Brian",
  "secondName": "Josue",
  "lastName": "Ramos",
  "email": "brian@email.com",
  "password": "admin123",
  "phoneNumber": 12345678,
  "address": "San Pedro Sula"
}
### Modificar un customer
PATCH http://localhost:1234/customers/853e982c-80ec-11ee-b53e-eaf15ba8dff1
Content-Type: application/json

{
  "firstName": "Brayan"
}

### Borrar un customer
DELETE  http://localhost:1234/customers/853e982c-80ec-11ee-b53e-eaf15ba8dff1