### Home
GET http://localhost:1234
### Customers
GET http://localhost:1234/customers
### Customers by ID
GET http://localhost:1234/customers/e1520fba-80af-11ee-bfd1-900f0c66a857
### Customers by address
GET http://localhost:1234/customers?address=Villanueva
### Crear un customer
POST http://localhost:1234/customers
Content-Type: application/json

{
  "firstName": "Daniel",
  "secondName": "Ajelandro",
  "lastName": "Corrales",
  "email": "daniel@gmail.com",
  "password": "admin123",
  "phoneNumber": 12345678,
  "address": "Villanueva"
}
### Crear un customer con errores
POST http://localhost:1234/customers
Content-Type: application/json

{
  "firstName": "Brian",
  "secondName": "Josue",
  "lastName": "Ramos",
  "email": "brian@email.com",
  "password": "admin123",
  "phoneNumber": 12345678,
  "address": "San Pedro Sula"
}
### Modificar un customer
PATCH http://localhost:1234/customers/1e61a006-80db-11ee-a5a1-900f0c66a857
Content-Type: application/json

{
  "firstName": "Daniel"
}

### Borrar un customer
DELETE  http://localhost:1234/customers/8c424794-80bc-11ee-bfd1-900f0c66a857